apiVersion: apps/v1
kind: Deployment
metadata:
  name: product decrease
  labels:
    app: product decrease
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product decrease
  template:
    metadata:
      labels:
        app: product decrease
    spec:
      containers:
        - name: product decrease
          image: "username/product decrease:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
